version: 0.0
os: linux
files:
  - source: /myapp
    destination: /root/myapp
hooks:
  BeforeInstall:
    - location: scripts/codedeploy/after-install.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/codedeploy/application-start.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/codedeploy/application-stop.sh
      timeout: 60
      runas: root
